language: python

dist: focal

python:
  - 3.10

env:
  - DJANGO=5.0.2

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=djangopoll,polls manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "Encrypted <access-key-id>=AKIA5FTY6LQERFDC2IPM"
  secret_access_key: 
    secure: "Encypted <secret-access-key>=v*1ns$8^s8isxj$-7c=f4%91gy3964s9sc%&90zb+6+wpiah*8"
  region: "us-west-2"
  app: "djangopoll"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-905418005513"
  on:
    repo: "wuyasan/swe1-app"
    branch: "main"
  
